echo "I am deceiving you, I am not innocent."
echo "I could have been a virus."
echo "I could have been a trojan."
echo "I could have been a malware."
echo "I could have been a ransomware."
echo "I could have been a spyware."
echo "I could have been a keylogger."
echo "I could have been a backdoor."
echo "I could have been a rootkit."
echo "I could have been a worm."
echo "I could have been a logic bomb."
echo "I could have been a time bomb."
echo "I could have been a boot sector virus."
echo "I could have been a macro virus."
echo "I could have been a file infector."
echo "I could have been a polymorphic virus."
echo "I could have been a metamorphic virus."
echo "I could have been a stealth virus."
echo "I could have been a armored virus."
echo "I could have been anything."
echo "The point is, don't run anything from internet right away, without knowing the contents of that script."